stages:
  main:
    cmd: python test.py --name coco_pretrained --dataset_mode coco --dataroot datasets/raw/coco_stuff
    deps:
      - checkpoints/coco_pretrained
      - datasets/raw/coco_stuff
      - test.py
    outs:
      - results
